// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241210093753_AddUsersToDb")]
    partial class AddUsersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2330),
                            Details = "Dummy Details",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa1.jpg",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Fireplace, Garden",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2418),
                            Details = "Charming cottage surrounded by nature.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa2.jpg",
                            Name = "Cozy Cottage",
                            Occupancy = 4,
                            Rate = 150.0,
                            Sqft = 450,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Beach Access, BBQ Area",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2429),
                            Details = "A villa with stunning ocean views.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa3.jpg",
                            Name = "Beachfront Bungalow",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 600,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Hiking Trails, Fireplace",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2440),
                            Details = "Peaceful retreat with breathtaking mountain views.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa4.jpg",
                            Name = "Mountain Retreat",
                            Occupancy = 5,
                            Rate = 250.0,
                            Sqft = 520,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Rooftop Terrace, High-Speed Wi-Fi",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2450),
                            Details = "Modern villa located in the heart of the city.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa4.jpg",
                            Name = "Cityscape Loft",
                            Occupancy = 3,
                            Rate = 180.0,
                            Sqft = 400,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Kayak Rental, Fishing Dock",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2459),
                            Details = "Relaxing villa by the lake.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa5.jpg",
                            Name = "Lakeside Lodge",
                            Occupancy = 7,
                            Rate = 280.0,
                            Sqft = 700,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Pool, Outdoor Lounge",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2470),
                            Details = "Exotic villa in a desert landscape.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa4.jpg",
                            Name = "Desert Oasis",
                            Occupancy = 5,
                            Rate = 220.0,
                            Sqft = 550,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Library, Wine Cellar",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2481),
                            Details = "Elegant villa with historic charm.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa3.jpg",
                            Name = "Historic Manor",
                            Occupancy = 8,
                            Rate = 350.0,
                            Sqft = 800,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Outdoor Shower, Hammock",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2491),
                            Details = "Secluded villa surrounded by lush jungle.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa3.jpg",
                            Name = "Jungle Hideaway",
                            Occupancy = 4,
                            Rate = 170.0,
                            Sqft = 480,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Ski-in/Ski-out, Hot Tub",
                            CreatedDate = new DateTime(2024, 12, 10, 9, 37, 52, 145, DateTimeKind.Local).AddTicks(2502),
                            Details = "Cozy villa with stunning snowy views.",
                            ImageUrl = "http://dotnetmastery.com/bluevillaimages/villa4.jpg",
                            Name = "Snowy Chalet",
                            Occupancy = 6,
                            Rate = 310.0,
                            Sqft = 650,
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
